services:
  isaac_ros:
    image: isaac-ros-dev:latest
    container_name: isaac_ros_dev_container
    runtime: nvidia
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - HOST_USER_UID=996
      - HOST_USER_GID=996
      - USERNAME=admin
    volumes:
      - /home/zeul/workspaces/isaac_ros-dev:/workspaces/isaac_ros-dev
    entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
    command: bash -c "sleep infinity"
